# Generated by Django 4.2.30 on 2026-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('ingestion_job', 'row_number')},
        ),
    ]
