# Generated by Django 4.2.30 on 2026-05-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_rawrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='total_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='total_flagged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='total_parsed',
            field=models.IntegerField(default=0),
        ),
    ]
