# Generated by Django 4.2.30 on 2026-05-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='original_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('EDITED', 'Edited'), ('LOCKED', 'Locked'), ('DELETED', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='normalized_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='records.normalizedrecord'),
        ),
    ]
